"""PDF report generation from model run results.

Generates structured underwriting assessment reports using fpdf2.
Each report contains: patient summary, risk classification, survival
analysis, disease progression, SHAP explanation, and validation flags.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from io import BytesIO
from pathlib import Path

from fpdf import FPDF

logger = logging.getLogger(__name__)


@dataclass
class ReportData:
    """Data container for PDF report generation.

    Attributes:
        patient_id: Patient identifier.
        market: Market code.
        age: Patient age.
        sex: Patient sex.
        bmi: Body mass index.
        smoking_status: Smoking status.
        charlson_index: Charlson Comorbidity Index.
        n_diagnoses: Number of coded diagnoses.
        n_labs: Number of lab results.
        risk_probability: XGBoost predicted probability.
        risk_class: Risk classification label.
        concordance_index: Cox PH model concordance.
        median_survival: Predicted median survival years.
        dqs: Data Quality Score.
        dqs_tier: DQS tier.
        dqs_completeness: Completeness component.
        dqs_consistency: Consistency component.
        dqs_recency: Recency component.
        validation_recommendation: Validation layer recommendation.
        validation_explanation: Human-readable explanation.
        flags_triggered: List of triggered validation flags.
        top_features: List of (feature_name, importance) tuples.
        shap_waterfall_png: PNG bytes for SHAP waterfall plot.
        progression_png: PNG bytes for disease progression plot.
    """

    patient_id: str = ""
    market: str = ""
    age: int = 0
    sex: str = ""
    bmi: float = 0.0
    smoking_status: str = ""
    charlson_index: int = 0
    n_diagnoses: int = 0
    n_labs: int = 0
    risk_probability: float = 0.0
    risk_class: str = ""
    concordance_index: float = 0.0
    median_survival: float = 0.0
    dqs: float = 0.0
    dqs_tier: str = ""
    dqs_completeness: float = 0.0
    dqs_consistency: float = 0.0
    dqs_recency: float = 0.0
    validation_recommendation: str = ""
    validation_explanation: str = ""
    flags_triggered: list[str] = field(default_factory=list)
    top_features: list[tuple[str, float]] = field(default_factory=list)
    shap_waterfall_png: bytes | None = None
    progression_png: bytes | None = None


class UnderwritingReport(FPDF):
    """PDF report for a single patient underwriting assessment."""

    def __init__(self) -> None:
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 12)
        self.cell(
            0,
            10,
            "MedRisk-ADH | Underwriting Assessment Report",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(
            0,
            10,
            f"Page {self.page_no()}/{{nb}} | Generated by MedRisk-ADH v2.0.0 | Synthetic data only",
            align="C",
        )

    def _section_title(self, title: str) -> None:
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(230, 230, 240)
        self.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def _key_value(self, key: str, value: str) -> None:
        self.set_font("Helvetica", "B", 9)
        self.cell(60, 6, key, new_x="END")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")

    def _alert_box(self, text: str, severity: str = "warning") -> None:
        if severity == "danger":
            self.set_fill_color(255, 200, 200)
        elif severity == "warning":
            self.set_fill_color(255, 240, 200)
        else:
            self.set_fill_color(200, 255, 200)

        self.set_font("Helvetica", "B", 9)
        self.multi_cell(0, 6, text, fill=True)
        self.ln(2)


def generate_report(data: ReportData, output_path: str | Path) -> Path:
    """Generate a complete PDF underwriting report.

    Args:
        data: ReportData with all model outputs and patient information.
        output_path: File path for the output PDF.

    Returns:
        Path to the generated PDF file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = UnderwritingReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Patient Summary ---
    pdf._section_title("1. Patient Summary")
    pdf._key_value("Patient ID:", data.patient_id)
    pdf._key_value("Market:", data.market)
    pdf._key_value("Age / Sex:", f"{data.age} / {data.sex}")
    pdf._key_value("BMI:", f"{data.bmi:.1f}")
    pdf._key_value("Smoking:", data.smoking_status)
    pdf._key_value("Charlson Index:", str(data.charlson_index))
    pdf._key_value("Coded Diagnoses:", str(data.n_diagnoses))
    pdf._key_value("Lab Results:", str(data.n_labs))
    pdf.ln(3)

    # --- Validation Status (upfront — this is the differentiator) ---
    pdf._section_title("2. Data Quality & Validation")
    pdf._key_value("Data Quality Score:", f"{data.dqs:.2f} ({data.dqs_tier.upper()})")
    pdf._key_value("  Completeness:", f"{data.dqs_completeness:.2f}")
    pdf._key_value("  Consistency:", f"{data.dqs_consistency:.2f}")
    pdf._key_value("  Recency:", f"{data.dqs_recency:.2f}")
    pdf._key_value("Recommendation:", data.validation_recommendation.upper())

    if data.flags_triggered:
        pdf._key_value("Flags:", ", ".join(data.flags_triggered))

    if data.validation_recommendation == "reject_prediction":
        pdf._alert_box(data.validation_explanation, severity="danger")
    elif data.validation_recommendation == "review":
        pdf._alert_box(data.validation_explanation, severity="warning")
    else:
        pdf._alert_box("All validation checks passed.", severity="ok")
    pdf.ln(2)

    # --- Risk Classification ---
    pdf._section_title("3. Risk Classification")
    pdf._key_value("Risk Probability:", f"{data.risk_probability:.1%}")
    pdf._key_value("Risk Class:", data.risk_class)
    pdf.ln(2)

    # --- Top Risk Drivers ---
    if data.top_features:
        pdf._section_title("4. Top Risk Drivers (SHAP)")
        pdf.set_font("Helvetica", "", 9)
        for rank, (feat, imp) in enumerate(data.top_features[:10], 1):
            bar_len = min(imp * 200, 80)
            pdf.cell(8, 5, f"{rank}.", new_x="END")
            pdf.cell(55, 5, feat, new_x="END")
            pdf.set_fill_color(70, 130, 180)
            pdf.cell(bar_len, 5, "", fill=True, new_x="END")
            pdf.cell(20, 5, f"  {imp:.4f}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # --- SHAP Waterfall Plot ---
    if data.shap_waterfall_png:
        pdf._section_title("5. Individual Explanation (SHAP Waterfall)")
        img_stream = BytesIO(data.shap_waterfall_png)
        pdf.image(img_stream, w=180)
        pdf.ln(3)

    # --- Survival / Progression ---
    pdf._section_title("6. Survival & Disease Progression")
    pdf._key_value("Cox PH Concordance:", f"{data.concordance_index:.4f}")
    pdf._key_value("Median Survival:", f"{data.median_survival:.1f} years")

    if data.progression_png:
        img_stream = BytesIO(data.progression_png)
        pdf.image(img_stream, w=180)
    pdf.ln(3)

    # --- Disclaimer ---
    pdf._section_title("7. Disclaimer")
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(
        0,
        4,
        (
            "This report was generated from synthetic data using the MedRisk-ADH proof-of-concept "
            "framework. All patient records are fully synthetic and GDPR-safe. Results are for "
            "demonstration purposes only and must not be used for actual underwriting decisions. "
            "Model outputs require validation on real-world data before production deployment."
        ),
    )

    pdf.output(str(output_path))
    logger.info("PDF report generated: %s", output_path)
    return output_path
