#!/usr/bin/env python3
"""Generate docs/INDEX.md — the CureApp repo "node map".

Structure + file lists are derived from a live repo scan (git-tracked + untracked,
gitignore-respecting) so the map is always real and complete; the *meaning* (node
titles, summaries, "read when…", cross-links) is curated in docs/index_nodes.yaml.

Usage:
    python3 scripts/build_index.py            # (re)write docs/INDEX.md
    python3 scripts/build_index.py --check     # exit 1 if INDEX.md is stale

Each repo file is assigned to exactly one node (most-specific matching glob wins).
Files matching no node are reported as "unmapped"; globs matching nothing as "dead".
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "docs" / "index_nodes.yaml"
OUT = ROOT / "docs" / "INDEX.md"
BANNER = "<!-- GENERATED by scripts/build_index.py — do NOT edit by hand. " \
         "Curate nodes in docs/index_nodes.yaml, then re-run the script. -->"


def universe() -> list[str]:
    """All tracked + untracked-not-ignored files, repo-relative, sorted."""
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout.splitlines()
    return sorted({p for p in out if p.strip()})


def glob_to_re(g: str) -> re.Pattern:
    """Glob → regex. ** spans directories; * stays within a path segment."""
    i, out = 0, ["^"]
    while i < len(g):
        if g[i:i + 3] == "**/":
            out.append("(?:.*/)?"); i += 3
        elif g[i:i + 2] == "**":
            out.append(".*"); i += 2
        elif g[i] == "*":
            out.append("[^/]*"); i += 1
        elif g[i] == "?":
            out.append("[^/]"); i += 1
        else:
            out.append(re.escape(g[i])); i += 1
    out.append("$")
    return re.compile("".join(out))


def specificity(g: str) -> int:
    """Literal-character count — longer/more-literal globs win ties."""
    return len(g) - g.count("*") - g.count("?")


def main() -> int:
    cfg = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    ignore = [glob_to_re(g) for g in cfg.get("ignore", [])]
    groups = cfg.get("groups", [])
    nodes = cfg["nodes"]
    node_ids = {n["id"] for n in nodes}

    files = [f for f in universe() if not any(rx.match(f) for rx in ignore)]

    # compile globs per node; assign each file to the most-specific matching node
    compiled = {n["id"]: [(g, glob_to_re(g)) for g in n.get("globs", [])] for n in nodes}
    glob_hits: dict[tuple, int] = {}
    assigned: dict[str, list[str]] = {n["id"]: [] for n in nodes}
    unmapped: list[str] = []
    for f in files:
        best = None  # (specificity, node_id, glob)
        for n in nodes:
            for g, rx in compiled[n["id"]]:
                if rx.match(f):
                    cand = (specificity(g), n["id"], g)
                    if best is None or cand[0] > best[0]:
                        best = cand
        if best is None:
            unmapped.append(f)
        else:
            assigned[best[1]].append(f)
            glob_hits[(best[1], best[2])] = glob_hits.get((best[1], best[2]), 0) + 1

    # any glob that won zero files (note: a glob can match yet be out-specified)
    dead = []
    for n in nodes:
        for g, rx in compiled[n["id"]]:
            if not any(rx.match(f) for f in files):
                dead.append((n["id"], g))

    # validate edges point to real nodes
    bad_edges = [(n["id"], e) for n in nodes for e in n.get("edges", []) if e not in node_ids]

    # ---- render -------------------------------------------------------------
    L: list[str] = []
    L.append(f"# {cfg.get('title', 'Repo Node Map')}")
    L.append("")
    L.append(BANNER)
    L.append("")
    if cfg.get("intro"):
        L.append(cfg["intro"].strip())
        L.append("")
    mapped = sum(len(v) for v in assigned.values())
    L.append(f"*{len(nodes)} nodes · {mapped} files mapped"
             + (f" · ⚠ {len(unmapped)} unmapped" if unmapped else "")
             + ".*")
    L.append("")

    # quick lookup table
    L.append("## Quick lookup — read when…")
    L.append("")
    L.append("| When you need… | → node |")
    L.append("|---|---|")
    for n in nodes:
        if n.get("reads_for"):
            L.append(f"| {n['reads_for']} | [[{n['id']}]] |")
    L.append("")

    # nodes grouped
    order = {g: i for i, g in enumerate(groups)}
    for g in sorted({n.get("group", "Other") for n in nodes}, key=lambda x: order.get(x, 99)):
        L.append(f"## {g}")
        L.append("")
        for n in [x for x in nodes if x.get("group", "Other") == g]:
            fs = assigned[n["id"]]
            if n.get("globs"):
                head = f"### `{n['id']}` · {n['title']}  ({len(fs)} file{'s' if len(fs) != 1 else ''})"
            else:
                head = f"### `{n['id']}` · {n['title']}"
            L.append(head)
            if n.get("summary"):
                L.append(n["summary"].strip())
            if fs:
                shown = " · ".join(f"`{p}`" for p in fs[:14])
                if len(fs) > 14:
                    shown += f" · …(+{len(fs) - 14})"
                L.append(f"**Files:** {shown}")
            if n.get("note"):
                L.append(f"**Where:** {n['note'].strip()}")
            if n.get("edges"):
                L.append("**Related:** " + " · ".join(f"[[{e}]]" for e in n["edges"]))
            if n.get("reads_for"):
                L.append(f"**Read when:** {n['reads_for']}")
            L.append("")

    if unmapped:
        L.append("## ⚠ Unmapped files (not in any node — add a glob in index_nodes.yaml)")
        L.append("")
        for f in unmapped:
            L.append(f"- `{f}`")
        L.append("")

    content = "\n".join(L).rstrip() + "\n"

    # diagnostics to stderr/stdout
    print(f"nodes={len(nodes)} files_scanned={len(files)} mapped={mapped} "
          f"unmapped={len(unmapped)} dead_globs={len(dead)} bad_edges={len(bad_edges)}")
    for nid, g in dead:
        print(f"  dead glob: {nid}: {g}")
    for nid, e in bad_edges:
        print(f"  bad edge: {nid} -> {e}")
    for f in unmapped:
        print(f"  unmapped: {f}")

    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("\n❌ docs/INDEX.md is stale.")
            print("→ Run: python3 scripts/build_index.py && git add docs/INDEX.md")
            return 1
        print("✓ docs/INDEX.md up to date.")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
